HMMontajes/urls.py
"""
URL configuration for HMMontajes project.
"""
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from rest_framework.permissions import AllowAny

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('settlement/', include('settlement.urls')),
    path('workers/', include('workers.urls')),
    path('holidays/', include('holidays.urls')),
    path('payroll/', include('payroll.urls')),
    path('', lambda request: redirect('/workers/upload-signings'), name='index'),
    path('docs/', include_docs_urls(title='HM API', permission_classes=[AllowAny])),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

payroll/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'payrolls', views.PayrollView, 'payrolls')

urlpatterns = [
    path('api/v1/', include(router.urls)),
    path('api/v1/create/', views.create_payroll, name="create_payroll"),
    path('api/v1/export/', views.export_payroll, name="export_payroll"),
]

workers/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'workers', views.WorkerView, 'workers')
router.register(r'signings', views.SigningView, 'signings')

urlpatterns = [
    path('', views.index, name="worker_index"),
    path('view/<str:pk>', views.view, name="worker_view"),
    path('signings/', views.signings, name="signings_index"),
    path('upload-signings', views.upload_signings, name="upload_signings"),
    path('api/v1/', include(router.urls)),
    path('api/v1/import-signings/', views.import_signings, name="import_signings"),
]

workers/models.py
from django.db import models
from pytz import timezone

class Worker(models.Model):
    document = models.IntegerField()
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

class RawSignings(models.Model):
    folder_number = models.PositiveBigIntegerField()
    date_signed = models.DateTimeField()
    normalized_date_signed = models.DateTimeField(null=True)
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE, related_name='signings')
    SIGNED_TYPES = {
        "E": "Entrada",
        "S": "Salida",
    }
    signed_type = models.CharField(max_length=1, choices=SIGNED_TYPES)
    door = models.CharField(max_length=30)
    contract_number = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Raw signings'

    def get_original_normalized_date_signed(self):
        return self.normalized_date_signed.astimezone(timezone('America/Bogota'))
    
    def get_original_date_signed(self):
        return self.date_signed.astimezone(timezone('America/Bogota'))

workers/views.py
import base64
from datetime import datetime

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import redirect, render
from rest_framework import filters, viewsets
from rest_framework.decorators import action, api_view, parser_classes
from rest_framework.pagination import PageNumberPagination
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.response import Response

from .models import RawSignings, Worker
from .serializers import (
    RawSigningsSerializer,
    RawSigningsSerializerFull,
    WorkerSerializer,
    WorkersSerializer,
)
from .tasks import process_excel
from .utils import save_excel_file


def index(request):
    workers_list = Worker.objects.all()
    workers_per_page = 20
    paginator = Paginator(workers_list, workers_per_page)
    page = request.GET.get("page")
    try:
        workers = paginator.page(page)
    except PageNotAnInteger:
        workers = paginator.page(1)
    except EmptyPage:
        workers = paginator.page(paginator.num_pages)
    return render(request, "workers/index.html", {"workers": workers})


def view(request, pk):
    worker = Worker.objects.get(id=int(pk))
    raw_signings_list = (
        RawSignings.objects.filter(worker=worker).order_by("-date_signed").all()
    )
    raw_signings_per_page = 20
    paginator = Paginator(raw_signings_list, raw_signings_per_page)
    page = request.GET.get("page")
    try:
        raw_signings = paginator.page(page)
    except PageNotAnInteger:
        raw_signings = paginator.page(1)
    except EmptyPage:
        raw_signings = paginator.page(paginator.num_pages)
    context = {"worker": worker, "raw_signings": raw_signings}
    return render(request, "workers/view.html", context)


def signings(request):
    signings_list = RawSignings.objects.order_by("-date_signed").all()
    signings_per_page = 20
    paginator = Paginator(signings_list, signings_per_page)
    page = request.GET.get("page")
    try:
        signings = paginator.page(page)
    except PageNotAnInteger:
        signings = paginator.page(1)
    except EmptyPage:
        signings = paginator.page(paginator.num_pages)
    return render(request, "workers/signings.html", {"signings": signings})


def upload_signings(request):
    if request.method == "POST" and request.FILES["excel_file"]:
        excel_file = request.FILES["excel_file"]
        # file_path = save_excel_file(excel_file)
        file_data = base64.b64encode(excel_file.read()).decode("utf-8")
        data_task = {
            "file_data": file_data,
        }
        process_excel.apply_async(kwargs=data_task)
        return redirect("/settlement/")

    return render(request, "workers/upload_excel.html")


class WorkerView(viewsets.ModelViewSet):
    serializer_class = WorkersSerializer
    queryset = Worker.objects.all()
    filter_backends = [filters.OrderingFilter, filters.SearchFilter]
    ordering_fields = "__all__"
    ordering = ["name"]
    search_fields = ["name", "document"]
    pagination_class = PageNumberPagination
    pagination_class.page_size = 10
    pagination_class.max_page_size = 100
    pagination_class.page_size_query_param = "page_size"

    def get_serializer_class(self):
        if self.action == "retrieve":
            return WorkerSerializer
        return WorkersSerializer


class SigningView(viewsets.ModelViewSet):
    serializer_class = RawSigningsSerializer
    queryset = RawSignings.objects.all()
    filter_backends = [filters.OrderingFilter, filters.SearchFilter]
    ordering_fields = "__all__"
    ordering = ["worker__name", "-date_signed"]
    search_fields = ["worker__name", "worker__document"]
    pagination_class = PageNumberPagination
    pagination_class.page_size = 10
    pagination_class.max_page_size = 100
    pagination_class.page_size_query_param = "page_size"

    def get_serializer_class(self):
        if self.action == "list":
            return RawSigningsSerializerFull
        return RawSigningsSerializer

    def get_queryset(self):
        queryset = super().get_queryset()
        start_date = self.request.query_params.get("start_date", None)
        end_date = self.request.query_params.get("end_date", None)
        if start_date and end_date:
            start_date = datetime.strptime(start_date, "%Y-%m-%d").date()
            end_date = datetime.strptime(end_date, "%Y-%m-%d").date()
            queryset = queryset.filter(
                normalized_date_signed__range=(start_date, end_date)
            )
        return queryset

    @action(detail=False, methods=["DELETE"])
    def delete_all(self, request):
        self.get_queryset().delete()
        return Response(
            {"message": "Todos los fichajes han sido eliminados correctamente"},
            status=204,
        )


@api_view(["POST"])
@parser_classes([MultiPartParser, FormParser])
def import_signings(request, format=None):
    excel_file = request.FILES["excel_file"]
    # file_path = save_excel_file(excel_file)
    file_data = base64.b64encode(excel_file.read()).decode("utf-8")
    data_task = {
        "file_data": file_data,
    }
    process_excel.apply_async(kwargs=data_task)
    signings = RawSignings.objects.order_by("worker__name", "-date_signed").all()
    paginator = PageNumberPagination()
    paginator.page_size = 100
    result_page = paginator.paginate_queryset(signings, request)
    serializer = RawSigningsSerializerFull(result_page, many=True)
    return paginator.get_paginated_response(serializer.data)

workers/templates/workers/index.html
{% extends 'main.html' %}

{% block title %}Trabajadores{% endblock %}

{% block content %}
<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-6">
    <h2 class="font-semibold text-2xl text-black">Trabajadores</h2>
</div>

<div class="rounded-sm border border-cyan-900/50 bg-white px-5 pt-6 pb-2.5 shadow-md sm:px-7.5 xl:pb-1">
    <div class="max-w-full overflow-x-auto">
        <table class="w-full table-auto">
            <thead>
                <tr class="bg-gray-200 text-left">
                    <th class="py-4 px-4 font-medium text-black">C&eacute;dula</th>
                    <th class="py-4 px-4 font-medium text-black">Nombre</th>
                    <th class="py-4 px-4 font-medium text-black">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for worker in workers %}
                <tr>
                    <td class="border-b border-[#eee] py-3 px-4">{{ worker.document }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ worker.name }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">
                        <div class="flex items-center space-x-3 5">
                            <a href="{% url 'worker_view' worker.id %}" class="hover:text-primary">
                                <svg class="fill-current" width="18" height="18" viewBox="0 0 18 18" fill="none"
                                  xmlns="http://www.w3.org/2000/svg">
                                  <path
                                    d="M8.99981 14.8219C3.43106 14.8219 0.674805 9.50624 0.562305 9.28124C0.47793 9.11249 0.47793 8.88749 0.562305 8.71874C0.674805 8.49374 3.43106 3.20624 8.99981 3.20624C14.5686 3.20624 17.3248 8.49374 17.4373 8.71874C17.5217 8.88749 17.5217 9.11249 17.4373 9.28124C17.3248 9.50624 14.5686 14.8219 8.99981 14.8219ZM1.85605 8.99999C2.4748 10.0406 4.89356 13.5562 8.99981 13.5562C13.1061 13.5562 15.5248 10.0406 16.1436 8.99999C15.5248 7.95936 13.1061 4.44374 8.99981 4.44374C4.89356 4.44374 2.4748 7.95936 1.85605 8.99999Z"
                                    fill="" />
                                  <path
                                    d="M9 11.3906C7.67812 11.3906 6.60938 10.3219 6.60938 9C6.60938 7.67813 7.67812 6.60938 9 6.60938C10.3219 6.60938 11.3906 7.67813 11.3906 9C11.3906 10.3219 10.3219 11.3906 9 11.3906ZM9 7.875C8.38125 7.875 7.875 8.38125 7.875 9C7.875 9.61875 8.38125 10.125 9 10.125C9.61875 10.125 10.125 9.61875 10.125 9C10.125 8.38125 9.61875 7.875 9 7.875Z"
                                    fill="" />
                                </svg>
                            </a>
                            <!-- <button class="hover:text-primary">
                                <svg class="fill-current" width="18" height="18" viewBox="0 0 18 18" fill="none"
                                  xmlns="http://www.w3.org/2000/svg">
                                  <path
                                    d="M13.7535 2.47502H11.5879V1.9969C11.5879 1.15315 10.9129 0.478149 10.0691 0.478149H7.90352C7.05977 0.478149 6.38477 1.15315 6.38477 1.9969V2.47502H4.21914C3.40352 2.47502 2.72852 3.15002 2.72852 3.96565V4.8094C2.72852 5.42815 3.09414 5.9344 3.62852 6.1594L4.07852 15.4688C4.13477 16.6219 5.09102 17.5219 6.24414 17.5219H11.7004C12.8535 17.5219 13.8098 16.6219 13.866 15.4688L14.3441 6.13127C14.8785 5.90627 15.2441 5.3719 15.2441 4.78127V3.93752C15.2441 3.15002 14.5691 2.47502 13.7535 2.47502ZM7.67852 1.9969C7.67852 1.85627 7.79102 1.74377 7.93164 1.74377H10.0973C10.2379 1.74377 10.3504 1.85627 10.3504 1.9969V2.47502H7.70664V1.9969H7.67852ZM4.02227 3.96565C4.02227 3.85315 4.10664 3.74065 4.24727 3.74065H13.7535C13.866 3.74065 13.9785 3.82502 13.9785 3.96565V4.8094C13.9785 4.9219 13.8941 5.0344 13.7535 5.0344H4.24727C4.13477 5.0344 4.02227 4.95002 4.02227 4.8094V3.96565ZM11.7285 16.2563H6.27227C5.79414 16.2563 5.40039 15.8906 5.37227 15.3844L4.95039 6.2719H13.0785L12.6566 15.3844C12.6004 15.8625 12.2066 16.2563 11.7285 16.2563Z"
                                    fill="" />
                                  <path
                                    d="M9.00039 9.11255C8.66289 9.11255 8.35352 9.3938 8.35352 9.75942V13.3313C8.35352 13.6688 8.63477 13.9782 9.00039 13.9782C9.33789 13.9782 9.64727 13.6969 9.64727 13.3313V9.75942C9.64727 9.3938 9.33789 9.11255 9.00039 9.11255Z"
                                    fill="" />
                                  <path
                                    d="M11.2502 9.67504C10.8846 9.64692 10.6033 9.90004 10.5752 10.2657L10.4064 12.7407C10.3783 13.0782 10.6314 13.3875 10.9971 13.4157C11.0252 13.4157 11.0252 13.4157 11.0533 13.4157C11.3908 13.4157 11.6721 13.1625 11.6721 12.825L11.8408 10.35C11.8408 9.98442 11.5877 9.70317 11.2502 9.67504Z"
                                    fill="" />
                                  <path
                                    d="M6.72245 9.67504C6.38495 9.70317 6.1037 10.0125 6.13182 10.35L6.3287 12.825C6.35683 13.1625 6.63808 13.4157 6.94745 13.4157C6.97558 13.4157 6.97558 13.4157 7.0037 13.4157C7.3412 13.3875 7.62245 13.0782 7.59433 12.7407L7.39745 10.2657C7.39745 9.90004 7.08808 9.64692 6.72245 9.67504Z"
                                    fill="" />
                                </svg>
                            </button> -->
                            <!-- <button class="hover:text-primary">
                                <svg class="fill-current" width="18" height="18" viewBox="0 0 18 18" fill="none"
                                  xmlns="http://www.w3.org/2000/svg">
                                  <path
                                    d="M16.8754 11.6719C16.5379 11.6719 16.2285 11.9531 16.2285 12.3187V14.8219C16.2285 15.075 16.0316 15.2719 15.7785 15.2719H2.22227C1.96914 15.2719 1.77227 15.075 1.77227 14.8219V12.3187C1.77227 11.9812 1.49102 11.6719 1.12539 11.6719C0.759766 11.6719 0.478516 11.9531 0.478516 12.3187V14.8219C0.478516 15.7781 1.23789 16.5375 2.19414 16.5375H15.7785C16.7348 16.5375 17.4941 15.7781 17.4941 14.8219V12.3187C17.5223 11.9531 17.2129 11.6719 16.8754 11.6719Z"
                                    fill="" />
                                  <path
                                    d="M8.55074 12.3469C8.66324 12.4594 8.83199 12.5156 9.00074 12.5156C9.16949 12.5156 9.31012 12.4594 9.45074 12.3469L13.4726 8.43752C13.7257 8.1844 13.7257 7.79065 13.5007 7.53752C13.2476 7.2844 12.8539 7.2844 12.6007 7.5094L9.64762 10.4063V2.1094C9.64762 1.7719 9.36637 1.46252 9.00074 1.46252C8.66324 1.46252 8.35387 1.74377 8.35387 2.1094V10.4063L5.40074 7.53752C5.14762 7.2844 4.75387 7.31252 4.50074 7.53752C4.24762 7.79065 4.27574 8.1844 4.50074 8.43752L8.55074 12.3469Z"
                                    fill="" />
                                </svg>
                            </button> -->
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        <div class="pagination">
            <span class="step-links">
                {% if workers.has_previous %}
                    <a href="?page=1">&laquo; primera</a>
                    <a href="?page={{ workers.previous_page_number }}">anterior</a>
                {% endif %}

                <span class="current">
                    P&aacute;gina {{ workers.number }} de {{ workers.paginator.num_pages }}.
                </span>

                {% if workers.has_next %}
                    <a href="?page={{ workers.next_page_number }}">siguiente</a>
                    <a href="?page={{ workers.paginator.num_pages }}">&uacute;ltima &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock %}

workers/templates/workers/signings.html
{% extends 'main.html' %}

{% block title %}Fichajes{% endblock %}

{% block content %}
<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-6">
    <h2 class="font-semibold text-2xl text-black">Fichajes</h2>
</div>

<div class="my-3">
    <a href="{% url 'upload_signings' %}" class="px-4 py-2 text-md font-semibold bg-blue-500 hover:bg-blue-300 text-white hover:text-gray-900 rounded-lg">Importar Fichajes</a>
</div>

<div class="rounded-sm border border-cyan-900/50 bg-white px-5 pt-6 pb-2.5 shadow-md sm:px-7.5 xl:pb-1">
    <div class="max-w-full overflow-x-auto">
        <table class="w-full table-auto">
            <thead>
                <tr class="bg-gray-200 text-left">
                    <th class="py-4 px-4 font-medium text-black">Legajo</th>
                    <th class="py-4 px-4 font-medium text-black">Trabajador</th>
                    <th class="py-4 px-4 font-medium text-black">C&eacute;dula</th>
                    <th class="py-4 px-4 font-medium text-black">Fecha Fichada</th>
                    <th class="py-4 px-4 font-medium text-black">Fecha Normalizada</th>
                    <th class="py-4 px-4 font-medium text-black">Tipo</th>
                    <th class="py-4 px-4 font-medium text-black">Puerta</th>
                    <th class="py-4 px-4 font-medium text-black">No. Contrato</th>
                </tr>
            </thead>
            <tbody>
                {% for signing in signings %}
                <tr>
                    <td class="border-b border-[#eee] py-3 px-4">{{ signing.folder_number }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ signing.worker }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ signing.worker.document }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ signing.date_signed }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ signing.normalized_date_signed }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ signing.get_signed_type_display }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ signing.door }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ signing.contract_number }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        <div class="pagination">
            <span class="step-links">
                {% if signings.has_previous %}
                    <a href="?page=1">&laquo; primera</a>
                    <a href="?page={{ signings.previous_page_number }}">anterior</a>
                {% endif %}

                <span class="current">
                    P&aacute;gina {{ signings.number }} de {{ signings.paginator.num_pages }}.
                </span>

                {% if signings.has_next %}
                    <a href="?page={{ signings.next_page_number }}">siguiente</a>
                    <a href="?page={{ signings.paginator.num_pages }}">&uacute;ltima &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock %}

workers/templates/workers/upload_excel.html
{% extends 'main.html' %}

{% block title %}Subir Fichajes{% endblock %}

{% block content %}
<h2>Subir archivo de Excel</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="excel_file" class="block text-sm font-medium text-gray-700 dark:text-white">Subir Fichajes</label>
    <div class="mt-1 relative rounded-md shadow-sm">
        <input type="file" name="excel_file" id="excel_file" accept=".xls,.xlsx" required class="sr-only">
        <div class="flex items-center">
            <label for="excel_file" class="cursor-pointer bg-gray-50 dark:bg-gray-700 py-2 px-4 border border-gray-300 rounded-md text-sm font-medium text-gray-700 dark:text-gray-100 hover:text-gray-300 focus:outline-none focus:border-blue-300 focus:ring focus:ring-blue-200 active:bg-gray-50 active:text-gray-800 dark:border-gray-400 dark:placeholder-gray-400">
                Buscar
            </label>
            <span class="py-1 px-4" id="fileName">Sin archivos seleccionados</span>
        </div>
    </div>
    <button type="submit" class="mt-1 px-4 py-2 text-sm font-semibold bg-blue-500 hover:bg-blue-300 text-white hover:text-gray-900 rounded-md">Importar</button>
</form>
<script>
    const fileInput = document.getElementById('excel_file');
    const fileName = document.getElementById('fileName');
  
    fileInput.addEventListener('change', () => {
        fileName.textContent = fileInput.files[0] ? fileInput.files[0].name : 'Sin archivos seleccionados';
    });
</script>
{% endblock %}

workers/templates/workers/view.html
{% extends 'main.html' %}

{% block title %}{{ worker.name }}{% endblock %}

{% block content %}
<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-6">
    <h2 class="font-semibold text-2xl text-black">{{ worker.name }}</h2>
</div>

<div class="flex flex-col">
    <div class="rounded-sm border border-cyan-900/50 bg-white px-5 py-5 shadow-md sm:px-7.5 mb-2">
        <div class="flex flex-col gap-2">
            <span class="font-medium">
                C&eacute;dula: {{worker.document}}
            </span>
        </div>
    </div>
</div>

<div class="rounded-sm border border-cyan-900/50 bg-white px-5 pt-6 pb-2.5 shadow-md sm:px-7.5">
    {% if not raw_signings %}
    <h3 class="bg-gray-200 text-gray-900 font-semibold text-center py-4">A&uacute;n no existen fichajes para el trabajador</h3>
    {% else %}
    <div class="max-w-full overflow-x-auto">
        <table class="w-full table-auto">
            <thead>
                <tr class="bg-gray-200 text-left">
                    <th class="py-4 px-4 font-medium text-black">Legajo</th>
                    <th class="py-4 px-4 font-medium text-black">Fecha Fichada</th>
                    <th class="py-4 px-4 font-medium text-black">Fecha Normalizada</th>
                    <th class="py-4 px-4 font-medium text-black">Tipo</th>
                    <th class="py-4 px-4 font-medium text-black">Puerta</th>
                    <th class="py-4 px-4 font-medium text-black">No. Contrato</th>
                </tr>
            </thead>
            <tbody>
                {% for raw_signing in raw_signings %}
                <tr>
                    <td class="border-b border-[#eee] py-3 px-4">{{ raw_signing.folder_number }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ raw_signing.date_signed }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ raw_signing.normalized_date_signed }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ raw_signing.get_signed_type_display }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ raw_signing.door }}</td>
                    <td class="border-b border-[#eee] py-3 px-4">{{ raw_signing.contract_number }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        <div class="pagination">
            <span class="step-links">
                {% if raw_signings.has_previous %}
                    <a href="?page=1">&laquo; primera</a>
                    <a href="?page={{ raw_signings.previous_page_number }}">anterior</a>
                {% endif %}

                <span class="current">
                    P&aacute;gina {{ raw_signings.number }} de {{ raw_signings.paginator.num_pages }}.
                </span>

                {% if raw_signings.has_next %}
                    <a href="?page={{ raw_signings.next_page_number }}">siguiente</a>
                    <a href="?page={{ raw_signings.paginator.num_pages }}">&uacute;ltima &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}